### PR TITLE
Allow input to be editable as text

### PR DESCRIPTION
**Pull request by dgalaktionov**
I really wanted to be able to type into the time box for my project, so I added this additional prop called "typeable", which allows to type into the input component.

While with this option it becomes possible to type in a time that is not consistent with the format (ie. 7:4 when the format is HH:mm), fixing that would require touching a lot of the existing code to treat the internal values as numbers instead of strings. Then the displayed time could be reformatted on dropdown blur.

### CODE REVIEW

**Comment by xxRockOnxx** [comment]
I really should start versioning this forked repo. It really just started off as my version that has disabled values and decided to share this but it seems like this is still somehow alive and people are using it.

Now back at this PR, may I know why you prefer the inputs as text?

If it's only for keyboard shortcut, I believe the much safer way to do it is to have a `<select>` element instead of list.

**Comment by dgalaktionov** [comment]
> I really should start versioning this forked repo. It really just started off as my version that has disabled values and decided to share this but it seems like this is still somehow alive and people are using it.

Well your fork looks like the only timepicker component that I could get working in a simple Vue2 + Browserify setup :laughing: 

> Now back at this PR, may I know why you prefer the inputs as text?
> 
> If it's only for keyboard shortcut, I believe the much safer way to do it is to have a `<select>` element instead of list.

How would you make two `<select>` (assuming one for hours and one for minutes) easily navigable with tab? Allowing for an option to make that `<input>` editable makes it really easy to alter the time without having to touch the mouse. What are you safety concerns, exactly?

**Comment by xxRockOnxx** [comment]
> How would you make two `<select>` (assuming one for hours and one for minutes) easily navigable with tab?

Am I missing something? isn't that its default behavior? 🤔

>  What are you safety concerns, exactly?
Nothing serious, just the format thing that you mentioned in the OP

**Comment by dgalaktionov** [comment]
You are right, `<select>` would work. Just tested it now :sweat_smile: 

I'll look into replacing those lists then, as long as you are okay with accepting a PR that completely reworks the template just to make it keyboard friendly :smiley: How do you think it should look? Keep the current `<input>` but display 2-4 `<select>` elements under it when focused?

**Comment by xxRockOnxx** [comment]
Yes that might work. I can also probably help you with the minor stuff if needed. The only thing that is important is to keep how the events work. A lot of people had downloaded from my repo and it would suck if we broke it without warning.

**Comment by dgalaktionov** [comment]
Done! Changes made:

- Replace `<ul>` and `<li>` by `<select>` and `<option>`, with some adjustments in CSS to make them look okay across browsers.
- Ensure that focus is properly managed. When the `<input>` is focused, the dropdown appears and the first `<select>` is focused (hours). When the focus is lost, the dropdown hides. This makes it work both with click and the tab key.
- Make the Esc key close the dropdown.

This components can be considered keyboard friendly now, and I have made sure that input and blur events are still properly emitted. I have tested it with Firefox, Chrome and Vivaldi.

The only thing I'm not quite satisfied with is the detection of lost focus. The `focusout` events are fired by the `<select>` elements and I'm capturing them in the dropdown `<div>`. There are three possible reasons for this event:

1. The focus was switched to another `<select>` from the component (as in picking minutes after having picked the hour).
2. The focus was switched to a DOM element outside the component with the tab key (cannot be done by clicking because the overlay prevents it).
3. The focus is out of the DOM. This usually happens when the browser tab is switched, or we have focused to another window.

I only want to hide the dropdown in the second case. In the third case I should just let the browser restore the focus on the same place as before the switch. To detect that third case I have to rely on the field `FocusEvent.relatedTarget` to be null, and otherwise check recursively its parents to make sure we have not switched the focus to another element inside the component. Let me know if you are aware of a less ugly way of doing this...

**Comment by xxRockOnxx** [comment]
thanks. Will look further into it this time tonight or maybe tomorrow morning before merging

**Pull request merged**
